version: '3'

services:
  tuna_events_consumer:
    image: ghcr.io/slip686/tuna_events_consumer:latest
    container_name: tuna_events_consumer
    restart: always
    environment:
      - KAFKA_HOST=kafka-0
      - KAFKA_PORT=9092
      - CH_HOST=clickhouse-node1
      - CH_TCP_PORT=9000
      - CH_HTTP_PORT=8123
      - CH_USER=admin
      - CH_PWD=123
      - CH_NAME=default
      - HOST=0.0.0.0
      - PORT=3041
    ports:
      - "3041:3041"
    networks:
      - kafka-ch

networks:
  kafka-ch:
